# Generated by Django 4.2.4 on 2023-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_profile_job_description_profile_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'full time'), ('Contract', 'contract'), ('Freelance', 'freelance')], default='1', max_length=20),
        ),
    ]
